server.port=8080

logging.file.name=./.logs/live-server.log
dead.queue.file.name=./.logs/dead-queue.log

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

rocketmq.name-server=localhost:9876
rocketmq.producer.group=event-consumer-group
rocketmq.producer.topic=event-topic
rocketmq.producer.dead-topic=dead-event-topic

mock.server.endpoint=http://localhost:9090/mock-api/